### ISSUE TITLE
Ocata: map_cell0 links to wrong path.

### ISSUE THREAD

**Issue by tgerdes** [salt-formulas/salt-formula-nova#26]
The state ``nova_controller_map_cell0`` calls  ``nova-manage cell_v2 map_cell0`` to create the initial mapping of cell0 in the api database.

This command will calculate the URL of the database from the connection setting (see [cell0_default_connection()](https://github.com/openstack/nova/blob/aaae213bf32096c56cb1bfcb4d0ac3cafd1c13fb/nova/cmd/manage.py#L1214) in nova.cmd.manage.py ) Arguably, the upstream function may have a bug in stable/ocata and master, but the this setting is defaulted as the following in ocata/nova-controller.conf.Debian :

```
connection = {{ controller.database.engine }}+pymysql://{{ controller.database.user }}:{{ controller.database.password }}@{{ controller.database.host }}/{{ controller.database.name }}?charset=utf8
```

Which when passed through cell0_default_connection() turns into 

```
{{ controller.database.engine }}+pymysql://{{ controller.database.user }}:{{ controller.database.password }}@{{ controller.database.host }}/{{ controller.database.name }}?charset=utf8{{ controller.database.name }}_cell0
```
because of the extra query param for "charset" the upstream code hadn't considered would be there.

Instead, it should be 

```
{{ controller.database.engine }}+pymysql://{{ controller.database.user }}:{{ controller.database.password }}@{{ controller.database.host }}/{{ controller.database.name }}_cell0?charset=utf8
```

This causes API calls to nova to fail until the URL is fixed in the database.

Alternatively the state could invoke map_cell0 with an explicit database path as an extra argument, which the user might want to specify at a custom URL in their pillar anyway.

**Comment by tgerdes** [comment]
Filed https://bugs.launchpad.net/nova/+bug/1696001 for the upstream issue.

**Comment by pupapaik** [comment]
We fixed that in the downstream packages as well. So MCP packages have this fix.

**Comment by tgerdes** [comment]
Cool, I'll drop this pull request then. Thanks! (Impressed at the nova devs for addressing it so fast)
