### ISSUE TITLE
libvirt_restart_systemd of a nova.compute conflicts with the same section in libvirt.server.service

### ISSUE THREAD

**Issue by AleksandrNull** [salt-formulas/salt-formula-nova#43]
Basically nova.compute libvirt_restart_systemd is a duplicate of a same section in libvirt.server.service. It should be removed with dependency on libvirt.server.service or the worst case/workaround - renamed to libvirt_restart_systemd_nova.

Implications: saltstack-nova formula couldn't be used together with libvirt formula

**Comment by Martin819** [comment]
This was already fixed by renaming the states accross the whole salt-formulas namespace.

Thanks for reporting this.
