### ISSUE TITLE
Pike nova-compute.conf duplicated configuration for vcpu_pin

### ISSUE THREAD

**Issue by gherr** [salt-formulas/salt-formula-nova#45]
Pike configuration files for both Debian and RedHat have duplicated vcpu_pin configuration 
around lines 500 and 600 including comment blocks. 
It seems that the same logic is implemented twice.
This does not affect the service and works ok, but the parameter should appear only once.

 grep -n vcpu nova/files/pike/nova-compute.conf.Debian 
478:#     vcpu_pin_set = "4-12,^8,15"
480:#vcpu_pin_set=<None>
481:{%- if compute.vcpu_pin_set is defined %}
482:vcpu_pin_set={{ compute.vcpu_pin_set }}
598:#     vcpu_pin_set = "4-12,^8,15"
600:{%- if compute.vcpu_pin_set is defined %}
601:vcpu_pin_set = {{ compute.vcpu_pin_set }}
603:#vcpu_pin_set=<None>

**Comment by Martin819** [comment]
This was fixed in https://github.com/salt-formulas/salt-formula-nova/commit/e2e30b2435248fb4f69e7e0d89b915079208ef91

Thanks for reporting this.
